---
- name: Playbook to install and configure Satellite Server
  # hosts: "{{ host | default('localhost') }}"
  hosts: localhost
  become: false

  tasks:

#    - name: Some debug
#      ansible.builtin.debug:
#        msg: env is {{ lookup('env', 'passwd' ) }} via extra-var {{ passwd }} of via extra_passwd {{ extra_passwd  }}

    - name: Some debug file
      ansible.builtin.debug:
        msg: file_content is {{ lookup('file', admin_password ) }} 

#    - name: Some debug extra_vars
#      ansible.builtin.debug:
#        msg: file_name on master is {{ admin_password  }} 

    - name: Some debug env 
      ansible.builtin.debug:
        msg: env is {{ lookup('env', 'admin_password' ) }} en {{ satgitops_admin_password }}



#file:
#  template.content_1: '{{ uc_content_1 }}'
#extra_vars:
#  uc_content_1: '{{ tower.filename.content_1 }}'
        
