---
- name: Playbook to install and configure Satellite Server
  # hosts: "{{ host | default('localhost') }}"
  hosts: localhost
  become: false
  vars:
     naam: "{{ lookup('env', 'THIRD_PARTY_CLOUD_API_TOKEN') }}"


  tasks:

    - name: Some debug
      ansible.builtin.debug:
        msg: "{{ naam }}"  
