---
- name: Playbook to install and configure Satellite Server
  # hosts: "{{ host | default('localhost') }}"
  hosts: localhost
  become: false

  tasks:

#    - name: Some debug
#      ansible.builtin.debug:
#        msg: env is {{ lookup('env', 'passwd' ) }} via extra-var {{ passwd }} of via extra_passwd {{ extra_passwd  }}

    - name: Some debuga file
      ansible.builtin.debug:
        msg: file_content is {{ lookup('file', uc_content_1 ) }} 

    - name: Some debug extra_vars
      ansible.builtin.debug:
        msg: file_name on master is {{ uc_content_1  }} 

    - name: Some debug env 
      ansible.builtin.debug:
        msg: env var uc_content is {{ lookup('env', 'uc_content_1' ) }} 
