---
- name: Playbook to install and configure Satellite Server
  # hosts: "{{ host | default('localhost') }}"
  hosts: localhost
  become: false
  vars:
     naam: "{{ lookup('ansible.builtin.vars', 'username') }}"


  tasks:

    - name: Some debug
      ansible.builtin.debug:
        msg: "{{ naam }}"  
