---
- name: Playbook to install and configure Satellite Server
  # hosts: "{{ host | default('localhost') }}"
  hosts: localhost
  become: false

  tasks:

#    - name: Some debug
#      ansible.builtin.debug:
#        msg: env is {{ lookup('env', 'passwd' ) }} via extra-var {{ passwd }} of via extra_passwd {{ extra_passwd  }}

    - name: Some debug file
      ansible.builtin.debug:
        msg: file_content is {{ lookup('file', admin_password ) }} 

    - name: Some debug file
      ansible.builtin.debug:
        msg: file_content is {{ lookup('file', manifest_uuid ) }} 

    - name: Some debug env 
      ansible.builtin.debug:
        msg: env is {{ lookup('env', 'admin_password' ) }} en {{ satgitops_admin_password }}

    - name: Some debug env 
      ansible.builtin.debug:
        msg: env is {{ lookup('env', 'manifest_uuid' ) }} en {{ satgitops_manifest_uuid }}


    - name: set_facts
      set_facts:
         admin_pass: "{{ satgitops_admin_password }}"

    - debug: var=admin_pass     
