---
- name: Playbook to install and configure Satellite Server
  # hosts: "{{ host | default('localhost') }}"
  hosts: localhost
  become: false

  tasks:

    - name: set_facts
      set_fact:
         username: "{{ lookup('env' , 'THIRD_PARTY_CLOUD_API_TOKEN') }}"

    - debug: var=username     

# fields:
#   - id: username
#     type: string
#     label: Username
#   - id: password
#     type: string
#     label: Password
#     secret: true
# required:
#   - username
#   - password
# 
# env:
#   THIRD_PARTY_CLOUD_API_TOKEN: '{{ username }}'
# file:
#   template: |-
#     [mycloud]
#     token={{ username }}
# extra_vars:
#   some_extra_var: '{{ username }}:{{ username }}'
