---
- name: Playbook to install and configure Satellite Server
  # hosts: "{{ host | default('localhost') }}"
  hosts: localhost
  become: false

  tasks:



    - name: set_facts
      set_fact:
         admin_pass: "{{ satgitops_admin_password }}"
         uuid: "{{ satgitops_manifest_uuid }}"

    - debug: var=admin_pass     
    - debug: var=uuid    



#  Credential Types
#  Input configuration
#
#  fields:
#    - id: admin_password
#      type: string
#      label: admin password
#      secret: true
#      multiline: false
#    - id: manifest_uuid
#      type: string
#      label: manifest uuid
#      secret: true
#      multiline: false
#  
# 
#  Injector configuration
#
#  extra_vars:
#    satgitops_manifest_uuid: '{{ manifest_uuid }}'
#    satgitops_admin_password: '{{ admin_password }}'
#  
