---
- name: Playbook to install and configure Satellite Server
  # hosts: "{{ host | default('localhost') }}"
  hosts: localhost
  become: false
  vars:
     naam: "{{ lookup('env', 'THIRD_PARTY_CLOUD_API_TOKEN') }}"
     pipo: "{{ lookup('file', 'template') }}"


  tasks:

    - name: Some debug
      ansible.builtin.debug:
        msg: "{{ naam }} - {{ some_extra_var }} {{ pipo }} "  
